"""Minutes of Meeting export — xlsx/pdf/docx.

One shared assembly step (build_minutes_document) + three thin format
renderers, so the three formats can't drift out of sync with each other
(see fluidgo-mom-architecture-lld.md ADR-3 for the library choices —
openpyxl/python-docx have no real alternative worth scoring; reportlab was
picked over weasyprint specifically to avoid adding system-level Cairo/
Pango dependencies to the Docker image).

"Best practice minutes" shape, same for all three formats: header
(company/date/purpose) -> attendees (Us/Customer, name+email) ->
discussion points (point/owner/date/status) -> AI summary text -> footer.
"""
from dataclasses import dataclass
from io import BytesIO
from typing import Optional
from app.config import settings


@dataclass
class MinutesDocument:
    company: str
    date: str
    purpose: str
    meeting_type: str
    attendees_us: list
    attendees_customer: list
    discussion_points: list
    ai_mom_summary: Optional[str]
    mom_status: str
    finalized_note: str


def build_minutes_document(m) -> MinutesDocument:
    """m is a Meeting ORM row or a dict from _serialize_meeting_detail —
    both are read the same way below."""
    def g(key, default=None):
        return m.get(key, default) if isinstance(m, dict) else getattr(m, key, default)

    attendees = g("attendees") or []
    return MinutesDocument(
        company=g("company") or "",
        date=str(g("date") or ""),
        purpose=(g("meeting_purpose") or "").replace("_", " ").title(),
        meeting_type=g("meeting_type") or "",
        attendees_us=[a for a in attendees if a.get("side") == "us"],
        attendees_customer=[a for a in attendees if a.get("side") == "customer"],
        discussion_points=g("discussion_points") or [],
        ai_mom_summary=g("ai_mom_summary"),
        mom_status=g("mom_status") or "none",
        finalized_note="Finalized" if g("mom_status") == "finalized" else "Draft — not yet finalized",
    )


def _attendee_lines(attendees):
    return [f"{a.get('name','')} ({a.get('email') or 'no email'})" for a in attendees] or ["— none listed —"]


def render_xlsx(doc: MinutesDocument) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill

    wb = Workbook()
    ws = wb.active
    ws.title = "Minutes of Meeting"
    bold = Font(bold=True)
    header_fill = PatternFill("solid", fgColor="1A0B2E")
    header_font = Font(bold=True, color="FFFFFF")

    ws.append([f"{settings.APP_NAME} — Minutes of Meeting"])
    ws["A1"].font = Font(bold=True, size=14)
    ws.append([f"{doc.company}  ·  {doc.date}  ·  {doc.purpose}  ·  {doc.meeting_type}"])
    ws.append([])

    ws.append(["Attendees — Us"])
    ws.cell(ws.max_row, 1).font = bold
    for line in _attendee_lines(doc.attendees_us):
        ws.append([line])
    ws.append([])
    ws.append(["Attendees — Customer"])
    ws.cell(ws.max_row, 1).font = bold
    for line in _attendee_lines(doc.attendees_customer):
        ws.append([line])
    ws.append([])
    ws.append(["Discussion Points"])
    ws.cell(ws.max_row, 1).font = bold
    header_row = ws.max_row + 1
    ws.append(["Point", "Responsibility", "Target Date", "Status"])
    for c in ws[header_row]:
        c.font = header_font
        c.fill = header_fill
    if doc.discussion_points:
        for p in doc.discussion_points:
            resp = f"{p.get('responsibility_side','').title()}: {p.get('responsibility_name','')}"
            ws.append([p.get("point", ""), resp, p.get("target_date") or "", p.get("status", "open").title()])
    else:
        ws.append(["— none recorded —", "", "", ""])
    ws.append([])

    ws.append(["AI Minutes Summary"])
    ws.cell(ws.max_row, 1).font = bold
    ws.append([doc.ai_mom_summary or "— not generated —"])
    ws.append([])
    ws.append([f"Generated by {settings.APP_NAME} · {doc.finalized_note}"])

    for col, width in zip("ABCD", (50, 30, 16, 14)):
        ws.column_dimensions[col].width = width
    for row in ws.iter_rows():
        for c in row:
            c.alignment = Alignment(wrap_text=True, vertical="top")

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


def render_docx(doc: MinutesDocument) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor

    d = Document()
    d.add_heading(f"{settings.APP_NAME} — Minutes of Meeting", level=1)
    d.add_paragraph(f"{doc.company}  ·  {doc.date}  ·  {doc.purpose}  ·  {doc.meeting_type}")

    d.add_heading("Attendees", level=2)
    t = d.add_table(rows=1, cols=2)
    t.style = "Light Grid Accent 1"
    hdr = t.rows[0].cells
    hdr[0].text, hdr[1].text = "Us", "Customer"
    us_lines = _attendee_lines(doc.attendees_us)
    cust_lines = _attendee_lines(doc.attendees_customer)
    for i in range(max(len(us_lines), len(cust_lines))):
        row = t.add_row().cells
        row[0].text = us_lines[i] if i < len(us_lines) else ""
        row[1].text = cust_lines[i] if i < len(cust_lines) else ""

    d.add_heading("Discussion Points", level=2)
    dt = d.add_table(rows=1, cols=4)
    dt.style = "Light Grid Accent 1"
    for cell, text in zip(dt.rows[0].cells, ["Point", "Responsibility", "Target Date", "Status"]):
        cell.text = text
    if doc.discussion_points:
        for p in doc.discussion_points:
            row = dt.add_row().cells
            row[0].text = p.get("point", "")
            row[1].text = f"{p.get('responsibility_side','').title()}: {p.get('responsibility_name','')}"
            row[2].text = p.get("target_date") or ""
            row[3].text = p.get("status", "open").title()
    else:
        dt.add_row().cells[0].text = "— none recorded —"

    d.add_heading("AI Minutes Summary", level=2)
    d.add_paragraph(doc.ai_mom_summary or "— not generated —")

    footer = d.add_paragraph(f"Generated by {settings.APP_NAME} · {doc.finalized_note}")
    footer.runs[0].font.size = Pt(9)
    footer.runs[0].font.color.rgb = RGBColor(0x6B, 0x5F, 0x7A)

    buf = BytesIO()
    d.save(buf)
    return buf.getvalue()


def _styled_table(data, col_widths=None):
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib import colors
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1A0B2E")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E8DFF5")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F5FF")]),
    ]))
    return t


def render_pdf(doc: MinutesDocument) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

    buf = BytesIO()
    pdf = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title2", parent=styles["Heading1"], textColor=colors.HexColor("#1A0B2E"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#1A0B2E"), spaceBefore=12)
    body = styles["BodyText"]
    small = ParagraphStyle("Small", parent=styles["BodyText"], fontSize=8, textColor=colors.HexColor("#6B5F7A"))

    story = [
        Paragraph(f"{settings.APP_NAME} — Minutes of Meeting", title_style),
        Paragraph(f"{doc.company} · {doc.date} · {doc.purpose} · {doc.meeting_type}", body),
        Spacer(1, 10),
        Paragraph("Attendees", h2),
    ]
    att_table_data = [["Us", "Customer"]]
    us_lines = _attendee_lines(doc.attendees_us)
    cust_lines = _attendee_lines(doc.attendees_customer)
    for i in range(max(len(us_lines), len(cust_lines))):
        att_table_data.append([
            us_lines[i] if i < len(us_lines) else "",
            cust_lines[i] if i < len(cust_lines) else "",
        ])
    story.append(_styled_table(att_table_data))

    story.append(Paragraph("Discussion Points", h2))
    dp_data = [["Point", "Responsibility", "Target Date", "Status"]]
    if doc.discussion_points:
        for p in doc.discussion_points:
            dp_data.append([
                p.get("point", ""),
                f"{p.get('responsibility_side','').title()}: {p.get('responsibility_name','')}",
                p.get("target_date") or "",
                p.get("status", "open").title(),
            ])
    else:
        dp_data.append(["— none recorded —", "", "", ""])
    story.append(_styled_table(dp_data, col_widths=[70 * mm, 45 * mm, 25 * mm, 20 * mm]))

    story.append(Paragraph("AI Minutes Summary", h2))
    story.append(Paragraph((doc.ai_mom_summary or "— not generated —").replace("\n", "<br/>"), body))
    story.append(Spacer(1, 14))
    story.append(Paragraph(f"Generated by {settings.APP_NAME} · {doc.finalized_note}", small))

    pdf.build(story)
    return buf.getvalue()


# format -> (render_fn, mimetype, file_extension)
EXPORT_RENDERERS = {
    "xlsx": (render_xlsx, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
    "docx": (render_docx, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx"),
    "pdf":  (render_pdf,  "application/pdf", "pdf"),
}
